version: '3'
services:

  certbot:
    image: certbot/certbot
    volumes:
      - ./data_link/certbot/conf:/etc/letsencrypt
      - ./data_link/certbot/www:/var/www/certbot
    # command to keep issuing new SSL certificats
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:1.21.3
    container_name: nginx
    restart: always
    depends_on:
      - es01
      - flask_server
      - node_server
      - mongo_express
      - scraper
      - pgadmin
    volumes:
      - ./data_link/nginx:/etc/nginx/conf.d
      - ./data_link/certbot/conf:/etc/letsencrypt
      - ./data_link/certbot/www:/var/www/certbot
      - ./data_link/nginx-static:/usr/share/nginx/html
      - ./data_link/nginx-auth/.htpasswd:/etc/apache2/.htpasswd
    # reload nginx based on config
    # keep reloading nginx every 6h to acquire new ssl certificates
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    env_file:
      - env/elastic.env
    volumes:
      # bind mount - <host-folder>:<container-folder>
      # bind mount can be accessed on host computer, but changing data might invoke errors in container
      # bind mount - /home/ykb/persistant_data/elasticsearch:/usr/share/elasticsearch/data
      # volume - <volume-name>:<container-path>
      # currently using bind mount approach
      - ./data_link/es_index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
        #networks:
        #- elastic_mongo
   
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - env/mongo_db.env
    volumes:
      - ./data_link/mongo_db:/data/db
    ports:
      - 27017:27017
        #networks:
        #- elastic_mongo

  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    env_file:
      - env/postgres_db.env
    volumes:
      - ./data_link/postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres_db
    restart: always
    ports:
      - 5050:80
    env_file:
      - env/pgadmin.env
    volumes:
      - ./data_link/pgadmin:/var/lib/pgadmin

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - env/mongo_express.env


  flask_server:
    image: fiitteam8/flask_server:latest
    container_name: flask_server
    env_file:
      - env/flask.env
      - env/mongo_connection.env
      - env/elastic_connection.env
    ports:
      - 5000:5000
  
  node_server:
    image: fiitteam8/node_server:latest
    container_name: node_server
    ports:
      - 8080:8080

  scraper:
    container_name: scraper
    image: fiitteam8/news_scraper
    ports:
      - 6800:6800
    volumes:
      - ./data_link/scraper/scrapyd/scrapyd.conf:/myApp/scraper/scrapyd.conf
    env_file:
      - env/scraper.env
      - env/mongo_connection.env

  documentation:
    container_name: documentation
    image: fiitteam8/ams_team_documentation:latest
    ports:
      - 8888:8888

  #index_service:
   #image: fiitteam8/es_indexer:latest
   #container_name: index_service
   #env_file:
     #- mongo_db.env
   #depends_on:
     #- mongo_db
     #- es01
    #networks:
     #- elastic_mongo

#networks:
  #elastic_mongo:
    #driver: bridge

# WHEN USING index_service uncomment networks in mongo_db, es01 container and networks tag

