name: Deploy

on:
  push:
    branches: [ main ]

jobs:
            
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - name: Executing remote ssh docker deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_MACHINE }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /home/fiitkar/docker-folder/
          git fetch && git pull
          ./decrypt_env.sh ${{ secrets.ENV_PASSWORD }}
          docker-compose pull && docker-compose up --detach && docker system prune -f
          sh ./data_link/nginx/refresh-nginx.sh
